### ISSUE TITLE
Integration tests for minimina

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/minimina#60]
## Problem

MiniMina is starting to get pretty complex and needs some integration tests to ensure command changes/additions don't introduce any unexpected behavior.

## Acceptance Criteria

Integration testing that spins up a network with and without archive nodes and covers the basic commands we implement.

## Tasks
- [ ] Documentation/README to reflect the changes
- [ ] implement

**Comment by piotr-iohk** [comment]
There were some basic integration tests added in https://github.com/MinaFoundation/minimina/pull/83.
