### ISSUE TITLE
Add node interaction example to readme

### ISSUE THREAD

**Issue by Isaac-DeFrain** [MinaFoundation/minimina#77]
## Problem

There isn't an example node interaction in the readme.

## Acceptance Criteria

Clear example of node interaction in readme

## Tasks
- [ ] Add `node start`, `node stop`, etc command examples to README
- [ ] Explain the various node commands in README

**Comment by piotr-iohk** [comment]
Examples of node commands usage were added to https://github.com/MinaFoundation/minimina/wiki. PR: https://github.com/MinaFoundation/minimina/pull/81 will link them from README.
